import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css';
import { OktaAuth } from '@okta/okta-auth-js';
import { useEffect, useContext } from 'react';

import AuthContext from '../lib/context/authContext';


export default function Home() {

  //const authClient: OktaAuth = new OktaAuth(configOptions);
  // console.log('')
  const authClient: OktaAuth = useContext(AuthContext);
  useEffect(() => {

    const initiateAuth= async () => {
      console.log('authClient.isLoginRedirect() = ', authClient.isLoginRedirect())
      console.log('authClient.isAuthenticated()=', authClient.isAuthenticated());
      if (authClient.isLoginRedirect()) {
        try {
          await authClient.handleRedirect();
        } catch (e) {
          // log or display error details
        }
      } else if (!await authClient.isAuthenticated()) {
        // Start the browser based oidc flow, then parse tokens from the redirect callback url
        authClient.signInWithRedirect();
      } else {
        // User is authenticated
        console.log('user is authenticated=', authClient.getAccessToken());
    }
  }

  initiateAuth().catch(console.error);;
    
  },[])

 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
      </main>
    </>
  )
}
